#!/bin/csh -f

#set echo

#set title = "IPDv4_c768_gfdlmp_gfsic_ljz_rt2018_res"
#set title = "IPDv4_c384_gfdlmp_gfsic_ljz_rt2020_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2018_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2019_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2020_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2020_v15_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2020_v15_aero_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2021_v15_IC_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2021_v15_IC_ctrl_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2021_v15_IC_aero_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2021_v16_IC_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2021_v16_IC_aero_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2021_v16_IC_COSP_res"
#set title = "IPDv4_c768_gfdlmp_gfsic_ljz_rt2021_v16_IC_aero_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2021_v16_IC_ctrl_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2022_v16_IC_ctrl_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2022_v16_IC_cpsd_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2022_v16_IC_cpsd_inline_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2022_v16_IC_aero_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2022_v16_IC_aero_inline_res"
#set title = "IPDv4_c48_gfdlmp_gfsic_ljz_rt2022_v16_IC_v3_res"
#set title = "SHiELD_c48_gfsic_rt2023_aero"
#set title = "SHiELD_c48_gfsic_rt2023_cpsd"
#set title = "SHiELD_c48_gfsic_rt2023_aero_inline"
#set title = "SHiELD_c48_gfsic_rt2023_cpsd_inline"
#set title = "SHiELD_c48_gfsic_rt2023_aero_cosp"
#set title = "SHiELD_c48_gfsic_rt2023_cpsd_cosp"
#set title = "SHiELD_c48_gfsic_rt2023_aero_inline_cosp"
#set title = "SHiELD_c48_gfsic_rt2023_cpsd_inline_cosp"
#set title = "SHiELD_c48_gfsic_rt2024_aero"
#set title = "SHiELD_c48_gfsic_rt2024_aero_inline"
#set title = "SHiELD_c48_v2025"
#set title = "SHiELD_c48_v2025_inline"
set title = "SHiELD_p3_c48_v2025"

#set MEMO = "_rt2018_e2_res2"
#set MEMO = "_20190305mods_rt1_res2"
#set MEMO = "_20190305mods_rt2_res2"
#set MEMO = "_20190417mods_rt1_res2"
#set MEMO = "_20190417mods_rt2_res2"
#set MEMO = "_20190417mods_rt3_res2"
#set MEMO = "_20190417mods_rt4_res2"
#set MEMO = "_RT2018_res2"
#set MEMO = "_RT2019_res2"
#set MEMO = "_RT2019_e44_res4"
#set MEMO = "_RT2020_e005_res2"
#set MEMO = "_RT2020_e005_noinline_res2"
#set MEMO = "_RT2020_e007_res2"
#set MEMO = "_RT2020_e035_v15_res2"
#set MEMO = "_RT2020_e036_res2"
#set MEMO = "_RT2020_e053_res4"
#set MEMO = "_RT2020_e056_res2"
#set MEMO = "_RT2020_e058_res2"
#set MEMO = "_RT2020_e061_res2"
#set MEMO = "_RT2020_e067_res2"
#set MEMO = "_RT2020_e068_res2"
#set MEMO = "_RT2020_e069_res2"
#set MEMO = "_RT2020_e072_res2"
#set MEMO = "_RT2020_e080_res2"
#set MEMO = "_RT2021_e028_res2"
#set MEMO = "_RT2021_e037_res2"
#set MEMO = "_RT2021_e038_res2"
#set MEMO = "_RT2021_e042_res2"
#set MEMO = "_RT2021_e044_res2"
#set MEMO = "_RT2021_e052_res2"
#set MEMO = "_RT2021_e070_res2"
#set MEMO = "_RT2021_e071_res2"
#set MEMO = "_RT2021_e072_res2"
#set MEMO = "_RT2021_e076_res2"
#set MEMO = "_RT2021_e143_res2"
#set MEMO = "_RT2022_e001_res2"
#set MEMO = "_RT2022_e002_res2"
#set MEMO = "_RT2022_e007_res2"
#set MEMO = "_RT2022_e010_res2"
#set MEMO = "_RT2022_e011_res2"
#set MEMO = "_RT2022_e052_res2"
#set MEMO = "_RT2022_e053_res2"
#set MEMO = "_RT2022_e116_res2"
#set MEMO = "_RT2023_e001_res02"
#set MEMO = "_RT2023_e002_res02"
#set MEMO = "_RT2023_e039_res02"
#set MEMO = "_RT2024_e001_res02"
set MEMO = "_v2025_e0020_res02"

#set EXE = "x"
#set EXE = "20190305mods.rt1.x"
#set EXE = "20190305mods.rt2.x"
#set EXE = "20190417mods.rt1.x"
#set EXE = "20190417mods.rt2.x"
#set EXE = "20190417mods.rt3.x"
#set EXE = "20190417mods.rt4.x"
#set EXE = "RT2019.e43.x"
#set EXE = "RT2019.e44.x"
#set EXE = "RT2020.e005.x"
#set EXE = "RT2020.e007.x"
#set EXE = "RT2020.e035.x"
#set EXE = "RT2020.e036.x"
#set EXE = "RT2020.e053.x"
#set EXE = "RT2020.e056.x"
#set EXE = "RT2020.e058.x"
#set EXE = "RT2020.e061.x"
#set EXE = "RT2020.e067.x"
#set EXE = "RT2020.e068.x"
#set EXE = "RT2020.e069.x"
#set EXE = "RT2020.e072.x"
#set EXE = "RT2020.e080.x"
#set EXE = "RT2021.e028.x"
#set EXE = "RT2021.e037.x"
#set EXE = "RT2021.e038.x"
#set EXE = "RT2021.e042.x"
#set EXE = "RT2021.e044.x"
#set EXE = "RT2021.e070.x"
#set EXE = "RT2021.e071.x"
#set EXE = "RT2021.e072.x"
#set EXE = "RT2021.e076.x"
#set EXE = "RT2021.e143.x"
#set EXE = "RT2022.e001.x"
#set EXE = "RT2022.e002.x"
#set EXE = "RT2022.e007.x"
#set EXE = "RT2022.e010.x"
#set EXE = "RT2022.e011.x"
#set EXE = "RT2022.e052.x"
#set EXE = "RT2022.e053.x"
#set EXE = "RT2022.e116.x"
#set EXE = "RT2023.e001.x"
#set EXE = "RT2023.e002.x"
#set EXE = "RT2023.e039.x"
#set EXE = "RT2024.e001.x"
set EXE = "v2025.e0020.x"

set basescript = "RUN_${title}.csh"

#set DATE = "20160801.00Z"
#set DATE = "20190801.00Z"
set DATE = "20210401.00Z"

#set cluster = "c3"
#set cluster = "c4"
set cluster = "c5"
#set cluster = "c6"

set runname = SHiELD_${title}${MEMO}.${DATE}
echo $runname

# c768
#sed 's#NAME=20150801.00Z#NAME='$DATE'#g \
#     s#MEMO=_RT2018#MEMO='$MEMO'#g \
#     s#EXE=x#EXE='$EXE'#g \
#     s#set COMP = "prod"#set COMP = "debug"#g \
#     s#set days = "10"#set days = "0"#g \
#     s#set hours = "0"#set hours = "1"#g \
#     s#set layout_x = "24"#set layout_x = "12"#g \
#     s#set layout_y = "16"#set layout_y = "32"#g \
#     s#set nthreads = "4"#set nthreads = "2"#g \
#     s#set HYPT = "on"#set HYPT = "off"#g \
#     s#set NUM_TOT = 1#set NUM_TOT = 2#g \
#     s#set chksum_debug = ".false."#set chksum_debug = ".true."#g \
#     s#fv_debug = .F.#fv_debug = .T.#g' \
#$basescript >! ${runname}.csh

# c384
#sed 's#NAME=20150801.00Z#NAME='$DATE'#g \
#     s#MEMO=_RT2018#MEMO='$MEMO'#g \
#     s#EXE=x#EXE='$EXE'#g \
#     s#set COMP = "prod"#set COMP = "debug"#g \
#     s#set days = "10"#set days = "0"#g \
#     s#set hours = "0"#set hours = "1"#g \
#     s#set layout_x = "18"#set layout_x = "16"#g \
#     s#set layout_y = "12"#set layout_y = "10"#g \
#     s#set nthreads = "4"#set nthreads = "2"#g \
#     s#set HYPT = "on"#set HYPT = "off"#g \
#     s#set NUM_TOT = 1#set NUM_TOT = 2#g \
#     s#set chksum_debug = ".false."#set chksum_debug = ".true."#g \
#     s#fv_debug = .F.#fv_debug = .T.#g' \
#$basescript >! ${runname}.csh

# c48 c4
if ( $cluster == "c4" ) then
	sed 's#NAME=20150801.00Z#NAME='$DATE'#g \
	     s#MEMO=_RT2018#MEMO='$MEMO'#g \
	     s#EXE=x#EXE='$EXE'#g \
	     s#SBATCH --cluster=c4#SBATCH --cluster=c4#g \
	     s#SBATCH --export=CLU=c4#SBATCH --export=CLU=c4#g \
	     s#set COMP = "prod"#set COMP = "debug"#g \
	     s#set days = "10"#set days = "0"#g \
	     s#set hours = "0"#set hours = "1"#g \
	     s#set layout_x = "2"#set layout_x = "1"#g \
	     s#set layout_y = "2"#set layout_y = "4"#g \
	     s#set nthreads = "2"#set nthreads = "1"#g \
	     s#set HYPT = "on"#set HYPT = "off"#g \
	     s#set NUM_TOT = 1#set NUM_TOT = 2#g \
	     s#set chksum_debug = ".false."#set chksum_debug = ".true."#g \
	     s#fv_debug = .F.#fv_debug = .T.#g' \
	$basescript >! ${runname}.csh
endif

# c48 c5
if ( $cluster == "c5" ) then
	sed 's#NAME=20150801.00Z#NAME='$DATE'#g \
	     s#MEMO=_RT2018#MEMO='$MEMO'#g \
	     s#EXE=x#EXE='$EXE'#g \
	     s#SBATCH --cluster=c4#SBATCH --cluster=c5#g \
	     s#SBATCH --export=CLU=c4#SBATCH --export=CLU=c5#g \
	     s#set COMP = "prod"#set COMP = "debug"#g \
	     s#set days = "10"#set days = "0"#g \
	     s#set hours = "0"#set hours = "1"#g \
	     s#set layout_x = "2"#set layout_x = "2"#g \
	     s#set layout_y = "2"#set layout_y = "3"#g \
	     s#set nthreads = "2"#set nthreads = "2"#g \
	     s#set NUM_TOT = 1#set NUM_TOT = 2#g \
	     s#set chksum_debug = ".false."#set chksum_debug = ".true."#g \
	     s#fv_debug = .F.#fv_debug = .T.#g' \
	$basescript >! ${runname}.csh
endif

# c48 c6
if ( $cluster == "c6" ) then
	sed 's#NAME=20150801.00Z#NAME='$DATE'#g \
	     s#MEMO=_RT2018#MEMO='$MEMO'#g \
	     s#EXE=x#EXE='$EXE'#g \
	     s#SBATCH --cluster=c4#SBATCH --cluster=c6#g \
	     s#SBATCH --export=CLU=c4#SBATCH --export=CLU=c6#g \
	     s#SBATCH --account=gfdl_w#SBATCH --account=bil-coastal-gfdl#g \
	     s#set COMP = "prod"#set COMP = "debug"#g \
	     s#set days = "10"#set days = "0"#g \
	     s#set hours = "0"#set hours = "1"#g \
	     s#set layout_x = "2"#set layout_x = "2"#g \
	     s#set layout_y = "2"#set layout_y = "3"#g \
	     s#set nthreads = "2"#set nthreads = "2"#g \
	     s#set NUM_TOT = 1#set NUM_TOT = 2#g \
	     s#set chksum_debug = ".false."#set chksum_debug = ".true."#g \
	     s#fv_debug = .F.#fv_debug = .T.#g' \
	$basescript >! ${runname}.csh
endif

chmod 755 ${runname}.csh
sbatch --job-name=${runname} ${runname}.csh
#rm -f ${runname}.csh

exit 0
